import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#06090D] text-white/80 font-sans selection:bg-white/10 selection:text-white p-6 md:p-12 lg:p-24">
      <div className="max-w-4xl mx-auto">
        <div className="mb-12">
          <Link 
            href="/"
            className="inline-flex items-center gap-2 text-xs uppercase tracking-widest text-white/50 hover:text-white transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Terminal
          </Link>
        </div>

        <h1 className="text-4xl md:text-6xl font-extrabold tracking-tighter text-white mb-4">
          Terms & Conditions
        </h1>
        <div className="flex items-center gap-3 mb-12">
          <span className="text-[10px] uppercase tracking-[0.2em] px-3 py-1 bg-white/5 border border-white/10 rounded-full text-white/70">
            Last Updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
          </span>
          <span className="text-[10px] uppercase tracking-[0.2em] px-3 py-1 bg-red-500/10 border border-red-500/20 rounded-full text-red-400 font-bold">
            Strict Enforcement
          </span>
        </div>

        <div className="space-y-12 text-sm leading-relaxed text-white/70">
          <section>
            <h2 className="text-xl font-bold tracking-tight text-white mb-4 uppercase border-b border-white/10 pb-2">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using Axiom Terminal (the "Platform"), you unconditionally agree to these strict Terms and Conditions. If you do not agree with every provision in this document, you must cease use of the Platform immediately. Violation of any of these terms will result in immediate termination of access without notice or recourse.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold tracking-tight text-white mb-4 uppercase border-b border-white/10 pb-2">
              2. No Financial Advice Disclaimer
            </h2>
            <p className="mb-4">
              <strong>AXIOM TERMINAL IS NOT A FINANCIAL ADVISOR, BROKER, OR REGISTERED INVESTMENT ADVISOR.</strong>
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>All market analysis, trade setups, and insights provided are for informational and educational purposes only.</li>
              <li>None of the information constitutes personalized financial advice, trade recommendations, or solicitations to buy or sell assets.</li>
              <li>You are solely and fully responsible for any trades or investments you decide to make.</li>
              <li>We are not liable for any financial losses or damages incurred through the use of this Platform.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold tracking-tight text-white mb-4 uppercase border-b border-white/10 pb-2">
              3. Intellectual Property (Strictly Protected)
            </h2>
            <p className="mb-4">
              All content on Axiom Terminal is strictly proprietary. This includes, but is not limited to: AI outputs, trade setups, market narratives, UI/UX designs, algorithms, code, and logical architectures.
            </p>
            <p className="mb-2"><strong>Users may NOT:</strong></p>
            <ul className="list-disc pl-5 space-y-2 text-red-200/80">
              <li>Copy, replicate, or reproduce any part of the Platform.</li>
              <li>Resell, redistribute, or package our data or signals as their own.</li>
              <li>Attempt to reverse engineer the AI systems, algorithms, or platform structure.</li>
              <li>Use any data, text, or output generated by the Platform to train, test, or fine-tune other artificial intelligence models or algorithms.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold tracking-tight text-white mb-4 uppercase border-b border-white/10 pb-2">
              4. Prohibited Use
            </h2>
            <p className="mb-4">
              We employ zero tolerance for abuse. The following actions are explicitly banned:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Scraping:</strong> The use of bots, scripts, spiders, crawlers, or automated means to access, extract, or index data.</li>
              <li><strong>Reverse Engineering:</strong> Decompiling or disassembling any software or AI infrastructure.</li>
              <li><strong>API Abuse:</strong> Attempting to access unpublished endpoints, brute-forcing, or bypassing rate limits.</li>
              <li><strong>Cloning:</strong> Replicating the interface, features, or visual identity (UI/UX) of Axiom Terminal.</li>
              <li><strong>Commercial Redistribution:</strong> Forwarding AI outputs or setups to paid groups, Discord servers, or Telegram channels.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold tracking-tight text-white mb-4 uppercase border-b border-white/10 pb-2">
              5. Account Termination
            </h2>
            <p>
              Axiom Terminal reserves the absolute right to immediately suspend, ban, or terminate your access without prior notice or refund if we detect suspicious behavior, automated access, excessive irregular requests, scraping attempts, or any violation of these terms. Our internal security systems make the final determination on abusive behavior.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold tracking-tight text-white mb-4 uppercase border-b border-white/10 pb-2">
              6. Rate Limiting & Access Control
            </h2>
            <p>
              To protect the integrity of our AI infrastructure, we actively monitor usage. The Platform may dynamically throttle usage, restrict access, or block IP addresses at our sole discretion if request volumes exceed normal human interaction boundaries. 
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold tracking-tight text-white mb-4 uppercase border-b border-white/10 pb-2">
              7. AI Limitations Disclaimer
            </h2>
            <p>
              The market insights and setups are generated by artificial intelligence. AI is inherently probabilistic and may produce inaccurate, delayed, or illogical outputs (hallucinations). There is absolutely no guarantee of correctness, accuracy, or profitability. You must independently verify all data before executing any trade.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold tracking-tight text-white mb-4 uppercase border-b border-white/10 pb-2">
              8. Limitation of Liability
            </h2>
            <p>
              <strong>UNDER NO CIRCUMSTANCES SHALL AXIOM TERMINAL BE HELD LIABLE FOR ANY DAMAGES.</strong> This includes direct, indirect, incidental, consequential, or punitive damages. We assume strictly zero liability for trading losses, missed opportunities, software bugs, inaccurate AI signals, downtime, or platform outages.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold tracking-tight text-white mb-4 uppercase border-b border-white/10 pb-2">
              9. Data Usage
            </h2>
            <p>
              We monitor and log platform usage, user interactions, and request telemetry. This data is strictly utilized for security auditing, preventing abuse (such as scraping), and improving the underlying AI logic continuously. By using the Platform, you consent to this monitoring.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold tracking-tight text-white mb-4 uppercase border-b border-white/10 pb-2">
              10. Beta Status Clause
            </h2>
            <p>
              Axiom Terminal is currently deployed as an experimental beta product. Features, data pipelines, integrations, and AI models may break, shift, or be entirely removed at any time without prior warning. You accept the software "as is" and "as available".
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold tracking-tight text-white mb-4 uppercase border-b border-white/10 pb-2">
              11. Governing Law
            </h2>
            <p>
              These Terms shall be governed and construed in accordance with the laws of [Jurisdiction Placeholder], without regard to its conflict of law provisions. Any legal action or proceeding arising out of these terms shall be brought exclusively in the courts located in [Jurisdiction Placeholder].
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold tracking-tight text-white mb-4 uppercase border-b border-white/10 pb-2">
              12. Changes to Terms
            </h2>
            <p>
              We reserve the right to modify or replace these Terms at any time without notice. It is your responsibility to review these Terms periodically. Continued use of the Platform after any changes constitutes your explicit acceptance of the new Terms.
            </p>
          </section>
        </div>

        <div className="mt-20 pt-8 border-t border-white/10 text-center">
          <p className="text-xs text-white/30 uppercase tracking-widest font-mono">
            &copy; {new Date().getFullYear()} Axiom Terminal. All rights strictly reserved.
          </p>
        </div>
      </div>
    </div>
  );
}
